package com.example.sachin.lecturereminder.dbModel;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.sachin.lecturereminder.dbModel.classData;

import com.example.sachin.lecturereminder.dbModel.classDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig classDataDaoConfig;

    private final classDataDao classDataDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        classDataDaoConfig = daoConfigMap.get(classDataDao.class).clone();
        classDataDaoConfig.initIdentityScope(type);

        classDataDao = new classDataDao(classDataDaoConfig, this);

        registerDao(classData.class, classDataDao);
    }
    
    public void clear() {
        classDataDaoConfig.getIdentityScope().clear();
    }

    public classDataDao getClassDataDao() {
        return classDataDao;
    }

}
